package com.example.stack_over_pig.piglatin.nodo;

public enum TipoNodoSentencia {
    DECLARACION_VARIABLE,
    DECLARACION_ARREGLO,
    DECLARACION_STRUCT,
    ASIGNACION,
    INCREMENTO_DECREMENTO,
    CONDICIONAL,
    CICLO_DUM,
    CICLO_FACERE,
    CICLO_PER,
    LECTURA,
    ESCRITURA,
    INTERRUPCION_CICLO,
    LLAMADA_FUNCION_SENTENCIA,
    LLAMADA_METODO_SENTENCIA
}