package com.example.contacto_3xtrat3r3str3.piglatin.nodo;

public enum TipoNodoExpr {
    // LITERALES
    LITERAL_ENTERO, LITERAL_DECIMAL, LITERAL_TEXTO, LITERAL_CARACTER,
    LITERAL_BOOL,
    LISTA_LITERAL,
    UNARIA,

    // ACCESOS
    IDENTIFICADOR, ACCESO_ARRAY, ACCESO_ATRIBUTO,

    // OPERACIONES
    BINARIA, INCREMENTO_DECREMENTO,

    // LLAMADAS Y OBJETOS
    LLAMADA_FUNCION, LLAMADA_METODO, INSTANCIA_OBJETO
}