package com.example.contacto_3xtrat3r3str3.zetariano.nodo;

public enum TipoNodoExpr {
    //LITERALES
    LITERAL_ENTERO, LITERAL_DECIMAL, LITERAL_CADENA, LITERAL_CARACTER, LITERAL_BOOL, LITERAL_NULO,
    LISTA_LITERAL,

    //ACCESOS
    IDENTIFICADOR, ACCESO_ARRAY, ACCESO_ATRIBUTO,

    //OPERACIONES
    BINARIA, UNARIA, INCREMENTO_DECREMENTO, TERNARIA,

    //LLAMADAS Y CREACION DE OBJETOS
    LLAMADA_FUNCION, LLAMADA_METODO, INSTANCIA_OBJETO, ARREGLO_NUEVO
}